apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-10T16:34:06Z"
  name: carts-canary
  resourceVersion: "34548"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: f5d082f7-62ec-11ea-bf52-42010a80029c
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
